# ~/.tmuxinator/<%= name %>.yml

name: <%= name %>
root: ~/code/<%= name %>

pre: mkdir -p ~/Work/<%= name %>

windows:
  - main:
      layout: main-vertical
      panes:
        - vim
        - c
        - c
  - config:
